# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np
np.random.randn(3,3,3)

array([[[-1.18469242,  1.35236887, -1.19255532],
        [ 0.73567335,  0.44737981, -0.79121364],
        [ 2.31311021,  1.88826859,  1.16011311]],

       [[ 0.5723253 , -1.12797162, -0.02081411],
        [ 0.92563219,  1.34857031,  0.12639166],
        [ 0.62608702, -0.11649155,  0.59219886]],

       [[-1.22704781,  0.42867158, -0.85044179],
        [ 0.02780334,  0.28484752, -0.20127085],
        [-0.31410214, -0.19045422, -0.87627716]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
mat = np.zeros((8,8))
mat[1::2,::2] = 1
mat[::2,1::2] = 1
mat

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

# 5.  How to find common values between two arrays?

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
np.intersect1d(arr1,arr2)

array([3, 4, 5])

# 6.How to get the dates of yesterday, today and tomorrow?

# 7. Consider two random array A and B, check if they are equal

# 8.Create random vector of size 10 and replace the maximum value by 0 

# 9. How to print all the values of an array?

# 10.Subtract the mean of each row of a matrix

In [33]:
x = np.random.randn(5,5)
print(x)
y = x - x.mean()
print(y)

[[-0.14182163  1.13381177  0.18497792  0.72128589 -0.0404465 ]
 [-0.83049237 -0.11242309  0.76300283 -0.61673253 -0.02536659]
 [-0.34851952  1.72369032 -0.43710809  0.03584009  0.76207943]
 [-1.03937402 -0.49516961 -1.29240316 -0.44670163  0.03149472]
 [ 0.0625049  -0.08071521 -1.3771101  -1.48423004 -0.10222914]]
[[-0.00373541  1.27189798  0.32306414  0.85937211  0.09763971]
 [-0.69240616  0.02566312  0.90108904 -0.47864631  0.11271963]
 [-0.2104333   1.86177653 -0.29902188  0.1739263   0.90016564]
 [-0.90128781 -0.35708339 -1.15431695 -0.30861541  0.16958093]
 [ 0.20059112  0.05737101 -1.23902389 -1.34614382  0.03585708]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [55]:
a = np.random.randint(0,20,30)
print(a)
print(np.bincount(a).argmax())

[ 7 14  7  4 15 19  0  4  3 15 14  0 10 12 13 10 11  8 17 14  4  9  6 14
  6  2 14 17  4 12]
14


# 14.How to get the n largest values of an array

# 15.How to create a record array from a regular array?